<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="index.php">
        <img class="mr-1" src="images/bugsy.png" style="width: 50px;" alt=""> Tindew !</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mr-2 <?php if ($template == "userlist") : ?>active<?php endif ?>">
                    <a class="nav-link" href="/TINDEW">Userlist</a>
                </li>
               <?php if (!$_SESSION['connected']) : ?>
                    <li class="nav-item mr-2 <?php if ($template == "login-form") : ?>active<?php endif ?>">
                        <a class="nav-link" href="login-form.php">Log in</a>
                    </li>
                    <li class="nav-item mr-2 <?php if ($template == "signup-form") : ?>active<?php endif ?>">
                        <a class="nav-link" href="signup-form.php">Sign Up</a>
                    </li>
                <?php else : ?>
                    <li class="nav-item mr-2 <?php if ($template == "myprofile") : ?>active<?php endif ?>">
                        <a class="nav-link" href="index.php?page=UsersController&method=show&id=<?= $_SESSION['user']['id'] ?>">My profile</a>
                    </li>
                    <li class="nav-item mr-2">
                        <a class="nav-link" href="logout.php">Log out (<?= $_SESSION['user']['firstName'] . " " . $_SESSION['user']['lastName'] ?>)</a>
                    </li>
                <?php endif ?>
            </ul>
            
            <form action="search.php" method="post" class="form-inline my-2 my-lg-0">
                <input id="searchValue" name="searchValue" class="form-control mr-sm-2" type="text" placeholder="Search" value="<?php if (!empty($_POST['searchValue'])) : echo $_POST['searchValue'];
                                                                                                                                endif ?>">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
</header>