<main>
    <form action="login.php" method="post" class="container mt-5">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <?php if (!empty($_SESSION['flashes']['errors'])) : ?><div class="alert alert-danger" role="alert"><?php Session::displayErrors(); ?></div><?php
                                                                                                                                                            endif ?>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                </div>

                <div class="form-group text-center">
                    <button type="submit" class="btn btn-primary">Sign in</button>
                </div>
            </div>
            <div class="col-4"></div>
        </div>
    </form>
</main>