<main>
    <div class="row mt-5">
        <div class="col-1"></div>
        <div class="col-10 text-center">
            <img class="mb-3 border border-secondary" src="<?php if (!empty($user['avatar'])) : echo $user['avatar'];
                                                            else : echo "https://via.placeholder.com/130";
                                                            endif ?>" alt="His/her picture">
            <h2><?= $user['firstName'] . " " . $user['lastName'] ?></h2>
        </div>
        <div class="col-1"></div>
    </div>
</main>
<style>
    img.border {
        border-width: 3px !important;
    }
</style>