<main class="container mt-5">
    <?php if (!empty($found)) : ?>
        <div class="row mt-3">
        <?php foreach ($found as $index => $entry) : ?>
                <div class="col-5 m-2 border border-secondary text-center" style="border-radius: 90px; padding: 0; margin: 0">
                    <a href="profile.php?id=<?= $entry['id'] ?>">
                        <img class="float-left rounded-circle m-1" src="<?= $entry['avatar'] ?>" alt="His/her picture">
                        <h3 class="text-primary"><?= $entry['firstName'] . " " . $entry['lastName'] ?></h3>   
                    </a>
                </div>
        <?php endforeach ?>
        </div>
    <?php else : ?>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">No results.</div>
            <div class="col-4"></div>
        </div>
    <?php endif ?>
</main>
<style>
    div.border {
        border-width: 3px !important;
    }

    div.row:nth-of-type(even) div.border img{
        float: right !important;
    }

    div.border h3{
        padding-top: 50px !important;
    }
</style>