<main>
    <form action="signup.php" method="post" class="container mt-5">
        <?php if (!empty($_SESSION['flashes']['errors'])) : ?><div class="alert alert-danger" role="alert"><?php Session::displayErrors(); ?></div><?php
                                                                                                                                                    endif ?>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group col-md-6">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6"></div>
            <div class="form-group col-md-6">
                <label for="passwordConfirm">Confirm your password :</label>
                <input type="password" class="form-control" id="passwordConfirm" name="passwordConfirm" placeholder="Confirmation">
            </div>
        </div>
        
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="firstName">First name</label>
                <input type="text" class="form-control" id="firstName" name="firstName">
            </div>
            <div class="form-group col-md-6">
                <label for="lastName">Last name</label>
                <input type="text" class="form-control" id="lastName" name="lastName">
            </div>
        </div>
        
        <div class="form-row">
            <div class="form-group col-md-6">
            <label for="inputCity">City</label>
            <input type="text" class="form-control" id="inputCity">
            </div>
            <div class="form-group col-md-4">
            <label for="inputState">State</label>
            <select id="inputState" class="form-control">
                <option selected>Choose...</option>
                <option>...</option>
            </select>
            </div>
            <div class="form-group col-md-2">
            <label for="inputZip">Zip</label>
            <input type="text" class="form-control" id="inputZip">
            </div>
        </div>
        <div class="form-group">
            <div class="form-check">
            <input class="form-check-input" type="checkbox" id="gridCheck">
            <label class="form-check-label" for="gridCheck">
                Check me out
            </label>
            </div>
        </div>
        <div class="form-group text-center">
            <button type="submit" class="btn btn-primary">Sign up</button>
        </div>
    </form>
</main>