<main>
    <div class="container-fluid">
        <div class="row">
            <div class="col-1"></div>
            <div class="col-10">
                <div class="row">
                <?php foreach ($users as $index => $user) : ?>
                        <div class="col-xs-12 col-md-6 col-lg-4 col-xl-3">
                            <div class="card border-secondary m-3" style="max-width: 20rem;">
                                <div class="card-header text-white bg-secondary"><?= $user['firstName'] . " " . $user['lastName'] ?></div>
                                <div class="card-body text-center">
                                    <img class="rounded-circle mb-3" src="<?= $user['avatar'] ?>" alt="His/her picture">
                                    <p class="card-text"><?= $user['description'] ?></p>
                                    <a href="profile.php?id=<?= $user['id'] ?>" class="text-white btn btn-warning">See more</a>
                                </div>
                            </div>
                        </div>
                <?php endforeach ?>
                </div>
            </div>
            <div class="col-1"></div>
        </div>
    </div>
</main>